package asiainfo;

/**
 * Created by cuiyueyang on 2020/1/16.
 */
public class 中转 {
    String xml = "<AICRMSERVICE>" +
            "<PUB_INFO>" +
            "<SYS_OP_ID>20046725</SYS_OP_ID>" +
            "<SYS_PASSWORD>8323f15343239abb72885940220a4f3e</SYS_PASSWORD>" +
            "<OP_ID>10208042</OP_ID>" +
            "<OP_ORG_ID>0</OP_ORG_ID>" +
            "<CLIENT_IP/>" +
            "<MENU_ID>10000008</MENU_ID>" +
            "</PUB_INFO>" +
            "<REQUEST>"+
            "<BUSICODE>ESB_SO_GROUP_APPLY_SAVEAPPLY_003</BUSICODE>"+
            "<BUSIPARAMS>"+
            "<APPLY_NOTE>" +
            "<APPLY_ID>-1</APPLY_ID>" +
            "<APPLY_TYPE>11</APPLY_TYPE>" +
            "<CUST_ID>9130269593</CUST_ID>" +
            "<GROUP_ID>57171583006</GROUP_ID>" +
            "<GROUP_NAME>端到端业务测试_杭州</GROUP_NAME>" +
            "<APPLICANT_ID/>" +
            "<OPEN_TYPE>4</OPEN_TYPE>" +
            "<IS_PRE_SALE>N</IS_PRE_SALE>" +
            "<ACCT_INFO>" +
            "<ACCT_NAME>端到端业务测试_杭州(互联网专线)20200114180720</ACCT_NAME>" +
            "<PAY_TYPE>1</PAY_TYPE>" +
            "<PAY_CYCLE>1</PAY_CYCLE>" +
            "</ACCT_INFO>" +
            "<APPLY_MARKET_INFO>" +
            "<MARKET_KIND_LIST>" +
            "<MARKET_KIND_INFO>" +
            "<MARKET_ID>500300140000</MARKET_ID>" +
            "<MARKET_KIND_ID>500300140080</MARKET_KIND_ID>" +
            "<MARKET_FEE>0</MARKET_FEE>" +
            "<PUB_ATTR_LIST>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>881111333815</ATTR_ID>" +
            "<ATTR_VALUE>2020-01-14</ATTR_VALUE>" +
            "<ATTR_TEXT>2020-01-14</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000028</ATTR_ID>" +
            "<ATTR_VALUE>20045508</ATTR_VALUE>" +
            "<ATTR_TEXT>20045508</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000029</ATTR_ID>" +
            "<ATTR_VALUE>FW包振翔</ATTR_VALUE>" +
            "<ATTR_TEXT>FW包振翔</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000021</ATTR_ID>" +
            "<ATTR_VALUE>13473468598</ATTR_VALUE>" +
            "<ATTR_TEXT>13473468598</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000033</ATTR_ID>" +
            "<ATTR_VALUE>杭州移动</ATTR_VALUE>" +
            "<ATTR_TEXT>杭州移动</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000013</ATTR_ID>" +
            "<ATTR_VALUE>13473468598</ATTR_VALUE>" +
            "<ATTR_TEXT>13473468598</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "<PUB_ATTR_INFO>" +
            "<ATTR_ID>80000035</ATTR_ID>" +
            "<ATTR_VALUE>杭州移动</ATTR_VALUE>" +
            "<ATTR_TEXT>杭州移动</ATTR_TEXT>" +
            "<ATTR_TYPE>2</ATTR_TYPE>" +
            "</PUB_ATTR_INFO>" +
            "</PUB_ATTR_LIST>" +
            "<KIND_ROLE_LIST>" +
            "<KIND_ROLE_INFO>" +
            "<KIND_ROLE_ID>800015000007</KIND_ROLE_ID>" +
            "<ROLE_GROUP_ID>1</ROLE_GROUP_ID>" +
            "<IS_MAIN_ROLE>Y</IS_MAIN_ROLE>" +
            "<OFFER_LIST>" +
            "<OFFER_INFO>" +
            "<OFFER_ID>800010000013</OFFER_ID>" +
            "<IS_OLD>N</IS_OLD>" +
            "<PROD_LIST>" +
            "<PROD_INFO>" +
            "<PROD_ID>600000285440</PROD_ID>" +
            "</PROD_INFO>" +
            "<PROD_INFO>" +
            "<PROD_ID>301000114273</PROD_ID>" +
            "<PROD_ATTR_LIST>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>809250001672</ATTR_ID>" +
            "<ATTR_VALUE>0</ATTR_VALUE>" +
            "</PROD_ATTR_INFO>" +
            "</PROD_ATTR_LIST>" +
            "</PROD_INFO>" +
            "<PROD_INFO>" +
            "<PROD_ID>800060000015</PROD_ID>" +
            "<PROD_ATTR_LIST>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000369024</ATTR_ID>" +
            "<ATTR_VALUE>82818191</ATTR_VALUE>" +
            "<ATTR_TEXT>82818191</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000577696</ATTR_ID>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000439657</ATTR_ID>" +
            "<ATTR_VALUE>1</ATTR_VALUE>" +
            "<ATTR_TEXT>网站</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000439654</ATTR_ID>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000439653</ATTR_ID>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000439652</ATTR_ID>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000580033</ATTR_ID>" +
            "<ATTR_VALUE>0</ATTR_VALUE>" +
            "<ATTR_TEXT>不选择</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000008891</ATTR_ID>" +
            "<ATTR_VALUE>1</ATTR_VALUE>" +
            "<ATTR_TEXT>1</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000525728</ATTR_ID>" +
            "<ATTR_VALUE>0</ATTR_VALUE>" +
            "<ATTR_TEXT>0</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>809250000109</ATTR_ID>" +
            "<ATTR_VALUE>20</ATTR_VALUE>" +
            "<ATTR_TEXT>20</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>600000369025</ATTR_ID>" +
            "<ATTR_VALUE>浙江省杭州市上城区南星街道凤凰山东路城市家园北门对面路灯杆</ATTR_VALUE>" +
            "<ATTR_TEXT>浙江省杭州市上城区南星街道凤凰山东路城市家园北门对面路灯杆</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>809250001024</ATTR_ID>" +
            "<ATTR_VALUE>杭州移动</ATTR_VALUE>" +
            "<ATTR_TEXT>杭州移动</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "<PROD_ATTR_INFO>" +
            "<ATTR_ID>809250001025</ATTR_ID>" +
            "<ATTR_VALUE>13473468598</ATTR_VALUE>" +
            "<ATTR_TEXT>13473468598</ATTR_TEXT>" +
            "</PROD_ATTR_INFO>" +
            "</PROD_ATTR_LIST>" +
            "</PROD_INFO>" +
            "</PROD_LIST>" +
            "<PROMOTION_LIST>" +
            "<PROMOTION_INFO>" +
            "<PROMOTION_ID>301000026620</PROMOTION_ID>" +
            "<PROMOTION_ATTR_LIST>" +
            "<PROMOTION_ATTR_INFO>" +
            "<ATTR_ID>809250000406</ATTR_ID>" +
            "<ATTR_VALUE>0|2020-01-14|2020-12-31</ATTR_VALUE>" +
            "</PROMOTION_ATTR_INFO>" +
            "<PROMOTION_ATTR_INFO>" +
            "<ATTR_ID>809250000417</ATTR_ID>" +
            "<ATTR_VALUE>2</ATTR_VALUE>" +
            "<ATTR_TEXT>打折</ATTR_TEXT>" +
            "</PROMOTION_ATTR_INFO>" +
            "</PROMOTION_ATTR_LIST>" +
            "</PROMOTION_INFO>" +
            "</PROMOTION_LIST>" +
            "</OFFER_INFO>" +
            "</OFFER_LIST>" +
            "</KIND_ROLE_INFO>" +
            "</KIND_ROLE_LIST>" +
            "</MARKET_KIND_INFO>" +
            "</MARKET_KIND_LIST>" +
            "</APPLY_MARKET_INFO>" +
            "<FEE_DETAIL_LIST>" +
            "<FEE_DETAIL_INFO>" +
            "<APPLY_ID>-1</APPLY_ID>" +
            "<PRODUCT_ID>600000285440</PRODUCT_ID>" +
            "<FEE_AMOUNT>120000</FEE_AMOUNT>" +
            "<FACT_AMOUNT>0</FACT_AMOUNT>" +
            "<NUM>1</NUM>" +
            "<DISCOUNT>0</DISCOUNT>" +
            "</FEE_DETAIL_INFO>" +
            "</FEE_DETAIL_LIST>" +
            "</APPLY_NOTE>" +
            "<FEEDBACK_RECODE>" +
            "<FEEDBACK_STATE>3</FEEDBACK_STATE" +
            "</FEEDBACK_RECODE>" +
            "<ORDX_PROT_ID/>" +
            "</BUSIPARAMS>"+
            "</REQUEST>"+
            "</AICRMSERVICE>";
}
